version: '3.7'

services:
  web:
    container_name: tiendita.smartFood
    build: ./appDocker
    command: gunicorn tienda.wsgi:application --bind 0.0.0.0:3762
    volumes: 
      - ./app:/usr/src/appDocker
      - ./app/static:/usr/src/appDocker/static
      - media_volume:/usr/src/appDocker/media

    ports:
      - 80:8000
    depends_on:
      - mysql

    env_file:
      - ./appDocker/.env
    
    networks:
      local_network:
        ipv4_address: 172.28.1.1


  nginx:
    container_name: edshop.proxy
    build: ./nginx
    volumes:
      - ./app/static:/usr/src/appDocker/static
      - media_volume:/usr/src/appDocker/media
    ports:
      - "80:80"
    depends_on:
      - smartFood
    networks:
      local_network:
        ipv4_address: 172.28.1.3


  mysql:
    image: mysql:latest
    container_name: smartFood.mysql
    volumes:
      - db_data:/var/lib/mysql:rw
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    
    environment:
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_DATABASE: 'db_smartFood'
    ports:
      - "3306:3306"

    networks:
      local_network:
        ipv4_address: 172.28.1.2


volumes:
  static_volume:
  media_volume:
  db_data:

networks:
  local_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16





